name: Test

# Run this workflow every time a new commit pushed to main branch
on: 
  push:
    branches:
      - main

jobs:

  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
        
      # Python Dependency Installation
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"


      # Runs the test action
      - name: Install Chrome and web driver
        run: |
          google-chrome --version
          wget https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          rm chromedriver_linux64.zip
          export PATH=$PATH:/home/runner/work/git-action-test/git-action-test/ >> ~/.profile
          # ls
          # pwd
      - name: Setup MiniSLATE
        run: |
          git clone https://github.com/slateci/minislate.git
          cd minislate/
          ./minislate init --selenium
          cd ..
          
      - name: Run Test
        run:
          python seleniumTest.py